# Generated by Django 6.1 on 2026-08-07 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location_image',
            field=models.ImageField(blank=True, help_text='Photo representing the neighbourhood', null=True, upload_to='location/'),
        ),
        migrations.CreateModel(
            name='LocationAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('shopping', 'Shopping & Entertainment'), ('healthcare', 'Healthcare Facilities'), ('education', 'Educational Institutions'), ('connectivity', 'Connectivity & Access')], max_length=20)),
                ('items', models.TextField(help_text='Comma-separated list, e.g. Sarit Centre, Westgate Mall')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_advantages', to='portfolio.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
