# Generated by Django 6.1 on 2026-08-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_property_location_image_locationadvantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='booklet_pdf',
            field=models.FileField(blank=True, help_text='Downloadable brochure PDF', null=True, upload_to='booklets/'),
        ),
    ]
