# Generated by Django 6.1 on 2026-08-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_property_booklet_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='construction_percent',
            field=models.PositiveSmallIntegerField(default=60, help_text='Construction completion percentage'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='room_type',
            field=models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('construction', 'Construction Progress')], max_length=20),
        ),
    ]
