# Generated by Django 6.1 on 2026-08-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_property_construction_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='George Karanja', max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='owner/')),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
