# Generated by Django 6.1 on 2026-08-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolioowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioowner',
            name='homepage_background',
            field=models.ImageField(blank=True, help_text='Animated background photo for the portfolio homepage', null=True, upload_to='owner/'),
        ),
    ]
